# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Major.create(name: '경영학부', liberal: '0')
Major.create(name: '글로컬IT학과', liberal: '0')
Major.create(name: '디지털컨텐츠학과', liberal: '0')
Major.create(name: '사회과학부', liberal: '0')
Major.create(name: '사과부_사회학', liberal: '0')
Major.create(name: '사과부_경제학', liberal: '0')
Major.create(name: '사과부_정치학', liberal: '0')
Major.create(name: '사회복지학과', liberal: '0')
Major.create(name: '소프트웨어공학과', liberal: '0')
Major.create(name: '신문방송학과', liberal: '0')
Major.create(name: '신학과', liberal: '0')
Major.create(name: '영어학과', liberal: '0')
Major.create(name: '일어일본학과', liberal: '0')
Major.create(name: '정보통신공학과', liberal: '0')
Major.create(name: '중어중국학과', liberal: '0')
Major.create(name: '컴퓨터공학과', liberal: '0')
Major.create(name: '교양필수', liberal: '1')
Major.create(name: '채플', liberal: '1')
Major.create(name: '교양사회', liberal: '1')
Major.create(name: '교양인문', liberal: '1')
Major.create(name: '교양자연', liberal: '1')
Major.create(name: '사회진출실', liberal: '1')



Lecture.create(name: '마케팅조사방법론 (01)', major_id:'1', professor_id:'130')
Lecture.create(name: '마케팅조사방법론 (02)', major_id:'1', professor_id:'130')
Lecture.create(name: '경영통계 (01)', major_id:'1', professor_id:'196')
Lecture.create(name: '경영통계 (02)', major_id:'1', professor_id:'196')
Lecture.create(name: '경영정보학', major_id:'1', professor_id:'159')
Lecture.create(name: '시스템분석 및 설계', major_id:'1', professor_id:'76')
Lecture.create(name: '회계학1', major_id:'1', professor_id:'198')
Lecture.create(name: '경영조직론과 리더쉽', major_id:'1', professor_id:'15')
Lecture.create(name: '촉진관리', major_id:'1', professor_id:'130')
Lecture.create(name: '한국생협의 이해', major_id:'1', professor_id:'57')
Lecture.create(name: '한국생협의 이해', major_id:'1', professor_id:'138')
Lecture.create(name: '한국생협의 이해', major_id:'1', professor_id:'97')
Lecture.create(name: '한화갤러리아인턴십', major_id:'1', professor_id:'76')
Lecture.create(name: '한화갤러리아인턴십', major_id:'1', professor_id:'60')
Lecture.create(name: '인턴십 2', major_id:'1', professor_id:'196')
Lecture.create(name: '중급회계', major_id:'1', professor_id:'28')
Lecture.create(name: '협동조합경영학개론', major_id:'1', professor_id:'90')
Lecture.create(name: '협동조합경영학개론', major_id:'1', professor_id:'24')
Lecture.create(name: '협동조합경영학개론', major_id:'1', professor_id:'154')
Lecture.create(name: '경영의사결정론', major_id:'1', professor_id:'73')
Lecture.create(name: '셀프리더십', major_id:'1', professor_id:'107')
Lecture.create(name: '창업과 글로벌경영', major_id:'1', professor_id:'128')
Lecture.create(name: '글로컬 입문', major_id:'2', professor_id:'46')
Lecture.create(name: '지역IT탐방 (01)', major_id:'2', professor_id:'14')
Lecture.create(name: '지역IT탐방 (02)', major_id:'2', professor_id:'14')
Lecture.create(name: '컴퓨터구조', major_id:'2', professor_id:'145')
Lecture.create(name: '문제해결기초', major_id:'2', professor_id:'14')
Lecture.create(name: 'C 프로그래밍', major_id:'2', professor_id:'14')
Lecture.create(name: '객체지향프로그래밍', major_id:'2', professor_id:'46')
Lecture.create(name: '데이터베이스프로그래밍', major_id:'2', professor_id:'46')
Lecture.create(name: '세미나4 (01)', major_id:'2', professor_id:'14')
Lecture.create(name: '세미나4 (02)', major_id:'2', professor_id:'14')
Lecture.create(name: '해외IT탐방', major_id:'2', professor_id:'14')
Lecture.create(name: '실무프로젝트', major_id:'2', professor_id:'46')
Lecture.create(name: '운영체제론', major_id:'2', professor_id:'14')
Lecture.create(name: '데이터통신', major_id:'2', professor_id:'52')
Lecture.create(name: 'IT특강', major_id:'2', professor_id:'162')
Lecture.create(name: 'IT취업실무I', major_id:'2', professor_id:'115')
Lecture.create(name: 'IT취업실무I', major_id:'2', professor_id:'155')
Lecture.create(name: 'IT취업실무II', major_id:'2', professor_id:'14')
Lecture.create(name: 'IT취업실무II', major_id:'2', professor_id:'79')
Lecture.create(name: '사물인터넷', major_id:'2', professor_id:'115')
Lecture.create(name: '해부학과 표현', major_id:'3', professor_id:'13')
Lecture.create(name: '게임제작', major_id:'3', professor_id:'181')
Lecture.create(name: '3D 캐릭터 애니메이션', major_id:'3', professor_id:'183')
Lecture.create(name: '인턴십 세미나', major_id:'3', professor_id:'13')
Lecture.create(name: '디지털기초조형', major_id:'3', professor_id:'13')
Lecture.create(name: '3D모델링 (01)', major_id:'3', professor_id:'141')
Lecture.create(name: '3D모델링 (02)', major_id:'3', professor_id:'141')
Lecture.create(name: '영상디자인II', major_id:'3', professor_id:'174')
Lecture.create(name: '컨셉 아트', major_id:'3', professor_id:'136')
Lecture.create(name: '인턴십 I', major_id:'3', professor_id:'13')
Lecture.create(name: '인턴십II', major_id:'3', professor_id:'13')
Lecture.create(name: '디지털 음악 II', major_id:'3', professor_id:'66')
Lecture.create(name: '포트폴리오 I (01)', major_id:'3', professor_id:'13')
Lecture.create(name: '포트폴리오 I (02)', major_id:'3', professor_id:'141')
Lecture.create(name: '한중일 캐릭터비교', major_id:'3', professor_id:'141')
Lecture.create(name: '실험애니메이션', major_id:'3', professor_id:'208')
Lecture.create(name: '전공세미나 II (01)', major_id:'3', professor_id:'13')
Lecture.create(name: '전공세미나 II (02)', major_id:'3', professor_id:'141')
Lecture.create(name: '인턴십 III', major_id:'3', professor_id:'13')
Lecture.create(name: '컨텐츠제작프로젝트 2', major_id:'3', professor_id:'141')
Lecture.create(name: '다큐멘터리 기획 제작', major_id:'3', professor_id:'203')
Lecture.create(name: '글로벌 콘텐츠 비즈니스', major_id:'3', professor_id:'96')
Lecture.create(name: '디지털영상촬영', major_id:'3', professor_id:'37')
Lecture.create(name: '고급3D제작', major_id:'3', professor_id:'13')
Lecture.create(name: '대학과 사회', major_id:'4', professor_id:'184')
Lecture.create(name: '인턴쉽프로그램1', major_id:'4', professor_id:'184')
Lecture.create(name: 'NGO인턴십세미나', major_id:'4', professor_id:'16')
Lecture.create(name: 'NGO인턴십Ⅰ', major_id:'4', professor_id:'16')
Lecture.create(name: 'NGO인턴십Ⅱ', major_id:'4', professor_id:'16')
Lecture.create(name: 'NGO인턴십Ⅲ', major_id:'4', professor_id:'16')
Lecture.create(name: 'NGO인턴십Ⅳ', major_id:'4', professor_id:'16')
Lecture.create(name: '인턴쉽프로그램2', major_id:'4', professor_id:'184')
Lecture.create(name: '인턴쉽프로그램4', major_id:'4', professor_id:'184')
Lecture.create(name: '인권의 사회학', major_id:'4', professor_id:'184')
Lecture.create(name: '가족사회학', major_id:'4', professor_id:'163')
Lecture.create(name: '젠더사회학', major_id:'4', professor_id:'168')
Lecture.create(name: '역사사회학', major_id:'4', professor_id:'111')
Lecture.create(name: '산업 및 지역 경제학', major_id:'4', professor_id:'129')
Lecture.create(name: '인턴쉽프로그램3', major_id:'4', professor_id:'184')
Lecture.create(name: '경제학개론 (01)', major_id:'4', professor_id:'117')
Lecture.create(name: '경제학개론 (02)', major_id:'4', professor_id:'117')
Lecture.create(name: '사회과학을 위한 통계학', major_id:'4', professor_id:'129')
Lecture.create(name: '사회운동의 정치학', major_id:'4', professor_id:'84')
Lecture.create(name: '현대한국정치론', major_id:'4', professor_id:'176')
Lecture.create(name: '국제분쟁과 국제기구', major_id:'4', professor_id:'44')
Lecture.create(name: '동아시아 산업화와 국가', major_id:'4', professor_id:'77')
Lecture.create(name: '세미나지도4', major_id:'4', professor_id:'184')
Lecture.create(name: '미국정치론', major_id:'4', professor_id:'176')
Lecture.create(name: '계급과 계층', major_id:'4', professor_id:'16')
Lecture.create(name: 'NGO이해 및 NGO만들기', major_id:'4', professor_id:'98')
Lecture.create(name: 'NGO이해 및 NGO만들기', major_id:'4', professor_id:'40')
Lecture.create(name: '사회과학 원서 강독', major_id:'4', professor_id:'94')
Lecture.create(name: '재정학', major_id:'4', professor_id:'129')
Lecture.create(name: '거시경제학(국민소득론)', major_id:'4', professor_id:'117')
Lecture.create(name: '한일비교경제론', major_id:'4', professor_id:'32')
Lecture.create(name: '한국경제론', major_id:'4', professor_id:'129')
Lecture.create(name: '현대마르크스경제학', major_id:'4', professor_id:'47')
Lecture.create(name: '정치과정론', major_id:'4', professor_id:'59')
Lecture.create(name: '남북관계와 통일문제', major_id:'4', professor_id:'167')
Lecture.create(name: '자본주의의 이해', major_id:'4', professor_id:'117')
Lecture.create(name: '정치사상사', major_id:'4', professor_id:'121')
Lecture.create(name: '정치이론과 비교정치', major_id:'4', professor_id:'77')
Lecture.create(name: '분배와 복지의 경제학', major_id:'4', professor_id:'94')
Lecture.create(name: '비교사회체제론', major_id:'4', professor_id:'213')
Lecture.create(name: '사회이론의 이해', major_id:'4', professor_id:'144')
Lecture.create(name: '정치학세미나 I', major_id:'7', professor_id:'176')
Lecture.create(name: '경제학세미나 I', major_id:'6', professor_id:'117')
Lecture.create(name: '사회학세미나 I', major_id:'5', professor_id:'184')
Lecture.create(name: 'NGO사회교육특강2', major_id:'4', professor_id:'16')
Lecture.create(name: '국가론', major_id:'4', professor_id:'51')
Lecture.create(name: '사회학의 기초이해', major_id:'4', professor_id:'45')
Lecture.create(name: 'NGO실습', major_id:'4', professor_id:'16')
Lecture.create(name: '전자민주주의론', major_id:'4', professor_id:'199')
Lecture.create(name: '사회적 경제와 대안사회', major_id:'4', professor_id:'74')
Lecture.create(name: '몸의 사회학', major_id:'4', professor_id:'168')
Lecture.create(name: '인간행동과사회환경 (01)', major_id:'8', professor_id:'91')
Lecture.create(name: '인간행동과사회환경 (02)', major_id:'8', professor_id:'190')
Lecture.create(name: '사회복지자료분석론', major_id:'8', professor_id:'34')
Lecture.create(name: '사회복지조사론', major_id:'8', professor_id:'64')
Lecture.create(name: '사회복지법제', major_id:'8', professor_id:'137')
Lecture.create(name: '사회복지행정론', major_id:'8', professor_id:'36')
Lecture.create(name: '사회복지정책론', major_id:'8', professor_id:'137')
Lecture.create(name: '정신보건사회복지', major_id:'8', professor_id:'91')
Lecture.create(name: '지역사회복지론', major_id:'8', professor_id:'64')
Lecture.create(name: '사회복지현장실습 II', major_id:'8', professor_id:'91')
Lecture.create(name: '사회복지실천기술론 (01)', major_id:'8', professor_id:'164')
Lecture.create(name: '사회복지실천기술론 (02)', major_id:'8', professor_id:'164')
Lecture.create(name: '가족복지론', major_id:'8', professor_id:'41')
Lecture.create(name: '노인복지론', major_id:'8', professor_id:'64')
Lecture.create(name: '장애인복지론', major_id:'8', professor_id:'126')
Lecture.create(name: '아동복지론', major_id:'8', professor_id:'191')
Lecture.create(name: '의료사회사업론', major_id:'8', professor_id:'190')
Lecture.create(name: '사회복지현장실습 I (01)', major_id:'8', professor_id:'64')
Lecture.create(name: '사회복지현장실습 I (02)', major_id:'8', professor_id:'179')
Lecture.create(name: '사회적기업과 사회복지', major_id:'8', professor_id:'26')
Lecture.create(name: '사회복지윤리와 철학', major_id:'8', professor_id:'178')
Lecture.create(name: '국제사회와 사회복지', major_id:'8', professor_id:'25')
Lecture.create(name: '복지국가론', major_id:'8', professor_id:'172')
Lecture.create(name: '사례관리', major_id:'8', professor_id:'80')
Lecture.create(name: '세미나지도4 (01)', major_id:'8', professor_id:'91')
Lecture.create(name: '세미나지도4 (02)', major_id:'8', professor_id:'36')
Lecture.create(name: '인권과 사회복지', major_id:'8', professor_id:'157')
Lecture.create(name: '국제 사회복지실천을 위한 의사소통기술 입문', major_id:'8', professor_id:'64')
Lecture.create(name: '운영체제론', major_id:'9', professor_id:'65')
Lecture.create(name: '사물인터넷', major_id:'9', professor_id:'115')
Lecture.create(name: 'C프로그래밍Ⅱ (01)', major_id:'9', professor_id:'210')
Lecture.create(name: 'C프로그래밍Ⅱ (02)', major_id:'9', professor_id:'115')
Lecture.create(name: '웹페이지구축Ⅰ', major_id:'9', professor_id:'170')
Lecture.create(name: '자료구조론 (01)', major_id:'9', professor_id:'67')
Lecture.create(name: '자료구조론 (02)', major_id:'9', professor_id:'67')
Lecture.create(name: '컴퓨터네트워크', major_id:'9', professor_id:'115')
Lecture.create(name: 'UNIX', major_id:'9', professor_id:'67')
Lecture.create(name: '인터넷보안', major_id:'9', professor_id:'52')
Lecture.create(name: '데이터베이스실습', major_id:'9', professor_id:'210')
Lecture.create(name: '데이터베이스프로젝트', major_id:'9', professor_id:'210')
Lecture.create(name: '과정지도2', major_id:'9', professor_id:'210')
Lecture.create(name: '웹페이지구축III', major_id:'9', professor_id:'67')
Lecture.create(name: '과정지도4', major_id:'9', professor_id:'210')
Lecture.create(name: '고급웹프로그래밍 II', major_id:'9', professor_id:'133')
Lecture.create(name: '통계자료분석 및 실습', major_id:'9', professor_id:'156')
Lecture.create(name: '과정지도6', major_id:'9', professor_id:'133')
Lecture.create(name: '모바일 프로그래밍 I', major_id:'9', professor_id:'133')
Lecture.create(name: 'IT취업실무I', major_id:'9', professor_id:'115')
Lecture.create(name: 'IT취업실무I', major_id:'9', professor_id:'155')
Lecture.create(name: 'IT취업실무II', major_id:'9', professor_id:'14')
Lecture.create(name: 'IT취업실무II', major_id:'9', professor_id:'79')
Lecture.create(name: '고급 Java 프로그래밍', major_id:'9', professor_id:'133')
Lecture.create(name: '만화와 애니메이션', major_id:'10', professor_id:'86')
Lecture.create(name: '광고크리에이티브', major_id:'10', professor_id:'118')
Lecture.create(name: '미디어현장실습', major_id:'10', professor_id:'200')
Lecture.create(name: '광고실무론', major_id:'10', professor_id:'200')
Lecture.create(name: '미디어연구방법', major_id:'10', professor_id:'182')
Lecture.create(name: '언론의 역사', major_id:'10', professor_id:'22')
Lecture.create(name: '사진커뮤니케이션', major_id:'10', professor_id:'22')
Lecture.create(name: '영상분석과 비평', major_id:'10', professor_id:'135')
Lecture.create(name: '스피치커뮤니케이션 (01)', major_id:'10', professor_id:'200')
Lecture.create(name: '스피치커뮤니케이션 (02)', major_id:'10', professor_id:'200')
Lecture.create(name: '대중문화론', major_id:'10', professor_id:'50')
Lecture.create(name: '뉴미디어와 사회변동', major_id:'10', professor_id:'17')
Lecture.create(name: '대학과 사회', major_id:'10', professor_id:'182')
Lecture.create(name: '인턴십 프로그램I', major_id:'10', professor_id:'182')
Lecture.create(name: '인턴십 프로그램II', major_id:'10', professor_id:'182')
Lecture.create(name: '인턴십 프로그램III', major_id:'10', professor_id:'182')
Lecture.create(name: '창작과 글쓰기', major_id:'10', professor_id:'143')
Lecture.create(name: '졸업세미나 (01)', major_id:'10', professor_id:'182')
Lecture.create(name: '졸업세미나 (02)', major_id:'10', professor_id:'22')
Lecture.create(name: '출판기획과 마케팅', major_id:'10', professor_id:'4')
Lecture.create(name: '기사작성과 편집Ⅰ', major_id:'10', professor_id:'29')
Lecture.create(name: '인턴십 프로그램 IV', major_id:'10', professor_id:'182')
Lecture.create(name: '문화기획과 예술경영', major_id:'10', professor_id:'103')
Lecture.create(name: '공익광고캠페인', major_id:'10', professor_id:'146')
Lecture.create(name: '공연기획 및 제작', major_id:'10', professor_id:'201')
Lecture.create(name: '커뮤니케이션 사상사', major_id:'10', professor_id:'182')
Lecture.create(name: '영화론', major_id:'10', professor_id:'108')
Lecture.create(name: 'PR캠페인실습', major_id:'10', professor_id:'200')
Lecture.create(name: '미디어 효과론', major_id:'10', professor_id:'22')
Lecture.create(name: '매스컴 영어 (01)', major_id:'10', professor_id:'200')
Lecture.create(name: '매스컴 영어 (02)', major_id:'10', professor_id:'200')
Lecture.create(name: '영상제작실습 II', major_id:'10', professor_id:'106')
Lecture.create(name: '정치커뮤니케이션과 의제설정', major_id:'10', professor_id:'193')
Lecture.create(name: '뉴미디어와 수용자', major_id:'10', professor_id:'197')
Lecture.create(name: '논문지도I', major_id:'11', professor_id:'101')
Lecture.create(name: '논문지도Ⅱ', major_id:'11', professor_id:'11')
Lecture.create(name: '성서의 이해', major_id:'11', professor_id:'81')
Lecture.create(name: '구약성서의 이해', major_id:'11', professor_id:'42')
Lecture.create(name: '철학적신학', major_id:'11', professor_id:'93')
Lecture.create(name: '기독교상담심리', major_id:'11', professor_id:'147')
Lecture.create(name: '신학의 역사', major_id:'11', professor_id:'11')
Lecture.create(name: '신학적 인간학', major_id:'11', professor_id:'101')
Lecture.create(name: '창조적예배 4', major_id:'11', professor_id:'158')
Lecture.create(name: '창조적예배 4', major_id:'11', professor_id:'43')
Lecture.create(name: '신학과현장 II', major_id:'11', professor_id:'56')
Lecture.create(name: '신학과현장 II', major_id:'11', professor_id:'102')
Lecture.create(name: '종교, 예술과 함께 걷다', major_id:'11', professor_id:'81')
Lecture.create(name: 'Theological English II', major_id:'11', professor_id:'101')
Lecture.create(name: '미국문학개론', major_id:'12', professor_id:'187')
Lecture.create(name: '영화로 읽는 셰익스피어', major_id:'12', professor_id:'187')
Lecture.create(name: '영작문Ⅱ (01)', major_id:'12', professor_id:'58')
Lecture.create(name: '영작문Ⅱ (02)', major_id:'12', professor_id:'58')
Lecture.create(name: '영어독서지도', major_id:'12', professor_id:'27')
Lecture.create(name: '영어문장이해II', major_id:'12', professor_id:'27')
Lecture.create(name: '영미문학: 자연과 인간', major_id:'12', professor_id:'180')
Lecture.create(name: '영어로 읽는 한국', major_id:'12', professor_id:'8')
Lecture.create(name: '영미문학과 여성', major_id:'12', professor_id:'180')
Lecture.create(name: '미국문화와 사회', major_id:'12', professor_id:'187')
Lecture.create(name: '영어다독Ⅱ (01)', major_id:'12', professor_id:'8')
Lecture.create(name: '영어다독Ⅱ (02)', major_id:'12', professor_id:'180')
Lecture.create(name: '실용영문법 II', major_id:'12', professor_id:'8')
Lecture.create(name: '언어와 커뮤니케이션 2', major_id:'12', professor_id:'8')
Lecture.create(name: '영어교수법 II', major_id:'12', professor_id:'27')
Lecture.create(name: '서양문학의 흐름', major_id:'12', professor_id:'180')
Lecture.create(name: '영어발달사', major_id:'12', professor_id:'27')
Lecture.create(name: '일본어문법II', major_id:'13', professor_id:'1')
Lecture.create(name: '일본어회화 II (01)', major_id:'13', professor_id:'112')
Lecture.create(name: '일본어회화 II (02)', major_id:'13', professor_id:'112')
Lecture.create(name: '고급일본어Ⅰ(JPT)', major_id:'13', professor_id:'1')
Lecture.create(name: '일본학세미나', major_id:'13', professor_id:'1')
Lecture.create(name: '일본근현대문학의 이해', major_id:'13', professor_id:'78')
Lecture.create(name: '일본근현대사', major_id:'13', professor_id:'9')
Lecture.create(name: '일본인의 생활세계', major_id:'13', professor_id:'163')
Lecture.create(name: '한일교류론', major_id:'13', professor_id:'3')
Lecture.create(name: '일본사회론', major_id:'13', professor_id:'163')
Lecture.create(name: '일본지방론', major_id:'13', professor_id:'3')
Lecture.create(name: '일본학연습II', major_id:'13', professor_id:'9')
Lecture.create(name: '일본어스피치세미나Ⅰ', major_id:'13', professor_id:'112')
Lecture.create(name: '일본어청해(스크린일본어)', major_id:'13', professor_id:'112')
Lecture.create(name: '일본어작문', major_id:'13', professor_id:'112')
Lecture.create(name: '한일언어비교', major_id:'13', professor_id:'63')
Lecture.create(name: '세계와 일본', major_id:'13', professor_id:'166')
Lecture.create(name: '일본어표현연습', major_id:'13', professor_id:'112')
Lecture.create(name: '웹페이지 구축', major_id:'14', professor_id:'79')
Lecture.create(name: 'C프로그래밍Ⅱ (01)', major_id:'14', professor_id:'149')
Lecture.create(name: 'C프로그래밍Ⅱ (02)', major_id:'14', professor_id:'149')
Lecture.create(name: '논리회로실험', major_id:'14', professor_id:'173')
Lecture.create(name: '컴퓨터구조', major_id:'14', professor_id:'145')
Lecture.create(name: '통신이론', major_id:'14', professor_id:'173')
Lecture.create(name: '데이터통신', major_id:'14', professor_id:'52')
Lecture.create(name: '전공지도II (01)', major_id:'14', professor_id:'52')
Lecture.create(name: '전공지도II (02)', major_id:'14', professor_id:'79')
Lecture.create(name: '전공지도II (03)', major_id:'14', professor_id:'173')
Lecture.create(name: '객체지향시스템', major_id:'14', professor_id:'23')
Lecture.create(name: '리눅스 시스템', major_id:'14', professor_id:'52')
Lecture.create(name: '인터넷보안', major_id:'14', professor_id:'52')
Lecture.create(name: '통신개발프로젝트I (01)', major_id:'14', professor_id:'79')
Lecture.create(name: '통신개발프로젝트I (02)', major_id:'14', professor_id:'173')
Lecture.create(name: 'TCP/IP', major_id:'14', professor_id:'79')
Lecture.create(name: '네트워크프로그래밍', major_id:'14', professor_id:'52')
Lecture.create(name: '임베디드시스템 I', major_id:'14', professor_id:'145')
Lecture.create(name: '웹프로그래밍', major_id:'14', professor_id:'79')
Lecture.create(name: '졸업지도', major_id:'14', professor_id:'79')
Lecture.create(name: 'IT취업실무I', major_id:'14', professor_id:'115')
Lecture.create(name: 'IT취업실무I', major_id:'14', professor_id:'155')
Lecture.create(name: 'IT취업실무II', major_id:'14', professor_id:'14')
Lecture.create(name: 'IT취업실무II', major_id:'14', professor_id:'79')
Lecture.create(name: '중국사회조사연습', major_id:'15', professor_id:'161')
Lecture.create(name: '졸업논문지도', major_id:'15', professor_id:'161')
Lecture.create(name: '중국어II (01)', major_id:'15', professor_id:'160')
Lecture.create(name: '중국어II (02)', major_id:'15', professor_id:'160')
Lecture.create(name: '중국학개론', major_id:'15', professor_id:'122')
Lecture.create(name: '한문연습', major_id:'15', professor_id:'85')
Lecture.create(name: '중국어II연습', major_id:'15', professor_id:'160')
Lecture.create(name: '동아시아 산업화와 국가', major_id:'15', professor_id:'77')
Lecture.create(name: '중국어회화Ⅲ', major_id:'15', professor_id:'160')
Lecture.create(name: '중국문화산업', major_id:'15', professor_id:'54')
Lecture.create(name: '중국어 회화I', major_id:'15', professor_id:'160')
Lecture.create(name: '중국어 회화 I 연습', major_id:'15', professor_id:'105')
Lecture.create(name: '고급중국어회화', major_id:'15', professor_id:'160')
Lecture.create(name: '중국어 독해', major_id:'15', professor_id:'161')
Lecture.create(name: '세미나 II (01)', major_id:'15', professor_id:'161')
Lecture.create(name: '세미나 II (02)', major_id:'15', professor_id:'161')
Lecture.create(name: '세미나 II (03)', major_id:'15', professor_id:'161')
Lecture.create(name: '중국의 경제정책', major_id:'15', professor_id:'122')
Lecture.create(name: '중국현대문학의 세계', major_id:'15', professor_id:'105')
Lecture.create(name: '중국문헌강독', major_id:'15', professor_id:'122')
Lecture.create(name: '졸업지도', major_id:'15', professor_id:'85')
Lecture.create(name: '컴퓨터구조', major_id:'16', professor_id:'23')
Lecture.create(name: 'C프로그래밍Ⅱ', major_id:'16', professor_id:'155')
Lecture.create(name: '운영체제', major_id:'16', professor_id:'23')
Lecture.create(name: '신호 및 시스템', major_id:'16', professor_id:'55')
Lecture.create(name: '컴퓨터네트워크', major_id:'16', professor_id:'169')
Lecture.create(name: '윈도우즈프로그래밍', major_id:'16', professor_id:'55')
Lecture.create(name: '게임프로그래밍', major_id:'16', professor_id:'155')
Lecture.create(name: '임베디드리눅스', major_id:'16', professor_id:'169')
Lecture.create(name: '멀티미디어처리프로젝트', major_id:'16', professor_id:'55')
Lecture.create(name: '과정지도4', major_id:'16', professor_id:'55')
Lecture.create(name: '과정지도6', major_id:'16', professor_id:'169')
Lecture.create(name: '그래픽스프로젝트', major_id:'16', professor_id:'155')
Lecture.create(name: '졸업지도 2', major_id:'16', professor_id:'155')
Lecture.create(name: '모바일프로그래밍', major_id:'16', professor_id:'169')
Lecture.create(name: '입체영상제작', major_id:'16', professor_id:'18')
Lecture.create(name: 'C프로그래밍실습II', major_id:'16', professor_id:'155')
Lecture.create(name: 'IT취업실무I', major_id:'16', professor_id:'115')
Lecture.create(name: 'IT취업실무I', major_id:'16', professor_id:'155')
Lecture.create(name: 'IT취업실무II', major_id:'16', professor_id:'14')
Lecture.create(name: 'IT취업실무II', major_id:'16', professor_id:'79')
Lecture.create(name: '웹프로그래밍', major_id:'16', professor_id:'55')
Lecture.create(name: '말과글(01)', major_id:'17', professor_id:'92')
Lecture.create(name: '말과글(02)', major_id:'17', professor_id:'127')
Lecture.create(name: '말과글(03)', major_id:'17', professor_id:'134')
Lecture.create(name: '말과글(04)', major_id:'17', professor_id:'195')
Lecture.create(name: '말과글(05)', major_id:'17', professor_id:'204')
Lecture.create(name: '말과글(06)', major_id:'17', professor_id:'92')
Lecture.create(name: '말과글(07)', major_id:'17', professor_id:'127')
Lecture.create(name: '말과글(08)', major_id:'17', professor_id:'134')
Lecture.create(name: '말과글(09)', major_id:'17', professor_id:'195')
Lecture.create(name: '말과글(10)', major_id:'17', professor_id:'35')
Lecture.create(name: '말과글(11)', major_id:'17', professor_id:'92')
Lecture.create(name: '말과글(12)', major_id:'17', professor_id:'127')
Lecture.create(name: '말과글(13)', major_id:'17', professor_id:'134')
Lecture.create(name: '말과글(14)', major_id:'17', professor_id:'195')
Lecture.create(name: '말과글(15)', major_id:'17', professor_id:'35')
Lecture.create(name: '말과글(16)', major_id:'17', professor_id:'151')
Lecture.create(name: '말과글(17)', major_id:'17', professor_id:'116')
Lecture.create(name: '말과글(18)', major_id:'17', professor_id:'188')
Lecture.create(name: '대학생활세미나 II (01)', major_id:'17', professor_id:'13')
Lecture.create(name: '대학생활세미나 II (02)', major_id:'17', professor_id:'141')
Lecture.create(name: '대학생활세미나 II (03)', major_id:'17', professor_id:'55')
Lecture.create(name: '대학생활세미나 II (04)', major_id:'17', professor_id:'169')
Lecture.create(name: '대학생활세미나 II (05)', major_id:'17', professor_id:'115')
Lecture.create(name: '대학생활세미나 II (06)', major_id:'17', professor_id:'156')
Lecture.create(name: '대학생활세미나 II (07)', major_id:'17', professor_id:'52')
Lecture.create(name: '대학생활세미나 II (08)', major_id:'17', professor_id:'173')
Lecture.create(name: '대학생활세미나 II (09)', major_id:'17', professor_id:'46')
Lecture.create(name: '대학생활세미나 II (10)', major_id:'17', professor_id:'46')
Lecture.create(name: '대학생활세미나 II (11)', major_id:'17', professor_id:'27')
Lecture.create(name: '대학생활세미나 II (12)', major_id:'17', professor_id:'8')
Lecture.create(name: '대학생활세미나 II (13)', major_id:'17', professor_id:'163')
Lecture.create(name: '대학생활세미나 II (14)', major_id:'17', professor_id:'9')
Lecture.create(name: '대학생활세미나 II (15)', major_id:'17', professor_id:'128')
Lecture.create(name: '대학생활세미나 II (18)', major_id:'17', professor_id:'11')
Lecture.create(name: '대학생활세미나 II (19)', major_id:'17', professor_id:'50')
Lecture.create(name: '대학생활세미나 II (20)', major_id:'17', professor_id:'144')
Lecture.create(name: '대학생활세미나 II (21)', major_id:'17', professor_id:'176')
Lecture.create(name: '대학생활세미나 II (24)', major_id:'17', professor_id:'77')
Lecture.create(name: '대학생활세미나 II (25)', major_id:'17', professor_id:'94')
Lecture.create(name: '대학생활세미나 II (26)', major_id:'17', professor_id:'184')
Lecture.create(name: '대학생활세미나 II (27)', major_id:'17', professor_id:'172')
Lecture.create(name: '대학생활세미나 II (28)', major_id:'17', professor_id:'137')
Lecture.create(name: '대학생활세미나 II (29)', major_id:'17', professor_id:'178')
Lecture.create(name: '대학생활세미나 II (30)', major_id:'17', professor_id:'161')
Lecture.create(name: '대학생활세미나 II (32)', major_id:'17', professor_id:'73')
Lecture.create(name: '대학생활세미나 II (33)', major_id:'17', professor_id:'200')
Lecture.create(name: '대학생활세미나 II (34)', major_id:'17', professor_id:'81')
Lecture.create(name: '대학생활세미나 II (35)', major_id:'17', professor_id:'122')
Lecture.create(name: '시네마채플', major_id:'18', professor_id:'81')
Lecture.create(name: '세계의 종교', major_id:'18', professor_id:'6')
Lecture.create(name: '애니어그램', major_id:'18', professor_id:'123')
Lecture.create(name: '생활과 영성', major_id:'18', professor_id:'12')
Lecture.create(name: '불완전한 존재로 살아가기', major_id:'18', professor_id:'48')
Lecture.create(name: '언저리에서 만나는 종교', major_id:'18', professor_id:'48')
Lecture.create(name: '교회음악', major_id:'18', professor_id:'82')
Lecture.create(name: '표현예술치료', major_id:'18', professor_id:'142')
Lecture.create(name: '경배와 찬양', major_id:'18', professor_id:'6')
Lecture.create(name: '명상', major_id:'18', professor_id:'147')
Lecture.create(name: '종교간대화의 영성', major_id:'18', professor_id:'119')
Lecture.create(name: '종교학 특강', major_id:'18', professor_id:'147')
Lecture.create(name: '한국의 종교', major_id:'18', professor_id:'6')
Lecture.create(name: '스트레스 관리', major_id:'18', professor_id:'147')
Lecture.create(name: '스님과 함께 하는 채플', major_id:'18', professor_id:'6')
Lecture.create(name: '성공회 감사성찬례', major_id:'18', professor_id:'53')
Lecture.create(name: '연극채플', major_id:'18', professor_id:'158')
Lecture.create(name: '신학과 채플', major_id:'18', professor_id:'11')
Lecture.create(name: 'MBSR', major_id:'18', professor_id:'211')
Lecture.create(name: '성서와 함께', major_id:'18', professor_id:'6')
Lecture.create(name: '인권과평화', major_id:'19', professor_id:'33')
Lecture.create(name: '영상시대의이해', major_id:'19', professor_id:'31')
Lecture.create(name: '사회학개론', major_id:'19', professor_id:'68')
Lecture.create(name: '매스컴과 현대사회', major_id:'19', professor_id:'50')
Lecture.create(name: '경영학원론', major_id:'19', professor_id:'128')
Lecture.create(name: '아시아사회와 문화', major_id:'19', professor_id:'77')
Lecture.create(name: '환경과 인간', major_id:'19', professor_id:'72')
Lecture.create(name: '대중음악의이해', major_id:'19', professor_id:'148')
Lecture.create(name: '노래로 보는 한국사회', major_id:'19', professor_id:'120')
Lecture.create(name: '경제학개론', major_id:'19', professor_id:'139')
Lecture.create(name: '정치경제학', major_id:'19', professor_id:'10')
Lecture.create(name: '협동조합과 대안사회', major_id:'19', professor_id:'108')
Lecture.create(name: '정신건강', major_id:'19', professor_id:'189')
Lecture.create(name: '성 사랑 결혼', major_id:'19', professor_id:'30')
Lecture.create(name: '법학통론', major_id:'19', professor_id:'124')
Lecture.create(name: '살아있는 자연', major_id:'19', professor_id:'39')
Lecture.create(name: '여성과 인권', major_id:'19', professor_id:'131')
Lecture.create(name: '한국노동운동의 역사와 이론', major_id:'19', professor_id:'75')
Lecture.create(name: '팀창업입문', major_id:'19', professor_id:'159')
Lecture.create(name: '팀창업입문', major_id:'19', professor_id:'114')
Lecture.create(name: '팀창업입문', major_id:'19', professor_id:'62')
Lecture.create(name: '특강2:세계 기업의 역사', major_id:'19', professor_id:'153')
Lecture.create(name: '특강3:인문성과 시민성에 관한 세미나', major_id:'19', professor_id:'89')
Lecture.create(name: '여성운동: 인식과 실천', major_id:'19', professor_id:'207')
Lecture.create(name: '지역재단과 사회공헌', major_id:'19', professor_id:'216')
Lecture.create(name: '세상읽기와 글쓰기', major_id:'20', professor_id:'151')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'214')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'71')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'71')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'140')
Lecture.create(name: '더불어숲 인문학-청춘, 삶, 문학', major_id:'20', professor_id:'152')
Lecture.create(name: '더불어숲 인문학-삶을 위한 공부', major_id:'20', professor_id:'5')
Lecture.create(name: '더불어숲 인문학-역사 속을 걷다.', major_id:'20', professor_id:'205')
Lecture.create(name: '더불어숲 인문학-문학으로 읽는 인권', major_id:'20', professor_id:'187')
Lecture.create(name: '교양일본어 1', major_id:'20', professor_id:'70')
Lecture.create(name: '교양일본어 1', major_id:'20', professor_id:'20')
Lecture.create(name: '언어의 이해', major_id:'20', professor_id:'1')
Lecture.create(name: '서양사의 이해', major_id:'20', professor_id:'100')
Lecture.create(name: '교양중국어 초급', major_id:'20', professor_id:'202')
Lecture.create(name: '실용영어(TOEIC) I', major_id:'20', professor_id:'110')
Lecture.create(name: '역사속의 한국과 미국', major_id:'20', professor_id:'38')
Lecture.create(name: '교양합창II', major_id:'20', professor_id:'212')
Lecture.create(name: '한국소설산책', major_id:'20', professor_id:'83')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'214')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'214')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'214')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'58')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'215')
Lecture.create(name: '서양문학의 흐름', major_id:'20', professor_id:'180')
Lecture.create(name: '논리와 비판적 사고', major_id:'20', professor_id:'192')
Lecture.create(name: '문학과 영상', major_id:'20', professor_id:'116')
Lecture.create(name: '한국 도시공간의 역사와 문화경험', major_id:'20', professor_id:'95')
Lecture.create(name: '교양시사영어II', major_id:'20', professor_id:'27')
Lecture.create(name: '한국현대사', major_id:'20', professor_id:'205')
Lecture.create(name: '문화유산탐방', major_id:'20', professor_id:'109')
Lecture.create(name: '한국연극의 이해', major_id:'20', professor_id:'158')
Lecture.create(name: '시각문화와 예술', major_id:'20', professor_id:'185')
Lecture.create(name: '한국어II', major_id:'20', professor_id:'87')
Lecture.create(name: '종교와 예술', major_id:'20', professor_id:'49')
Lecture.create(name: '교양러시아어 I', major_id:'20', professor_id:'104')
Lecture.create(name: '사진으로 보는 한국근현대사', major_id:'20', professor_id:'95')
Lecture.create(name: '실용영어(TOEIC) 2', major_id:'20', professor_id:'110')
Lecture.create(name: '상상력과 창의력 -기획과 글쓰기', major_id:'20', professor_id:'194')
Lecture.create(name: '온라인 게임과 종교적 상징', major_id:'20', professor_id:'56')
Lecture.create(name: '한국어 교육방법론', major_id:'20', professor_id:'83')
Lecture.create(name: 'Fun English II', major_id:'20', professor_id:'58')
Lecture.create(name: '기초영문법 II', major_id:'20', professor_id:'27')
Lecture.create(name: '기초영문법 II', major_id:'20', professor_id:'171')
Lecture.create(name: '문예창작과 감상 II', major_id:'20', professor_id:'188')
Lecture.create(name: '문학비평의 방법과 실제', major_id:'20', professor_id:'152')
Lecture.create(name: 'LIfe Talk', major_id:'20', professor_id:'58')
Lecture.create(name: '인터넷과 글쓰기', major_id:'20', professor_id:'204')
Lecture.create(name: '한국인과 고전의 세계', major_id:'20', professor_id:'152')
Lecture.create(name: 'Business english', major_id:'20', professor_id:'214')
Lecture.create(name: 'English Speech II', major_id:'20', professor_id:'215')
Lecture.create(name: 'Intercultural Communication I', major_id:'20', professor_id:'214')
Lecture.create(name: 'Internet English', major_id:'20', professor_id:'215')
Lecture.create(name: 'Global Career and Leadership II', major_id:'20', professor_id:'215')
Lecture.create(name: '책의문화사', major_id:'20', professor_id:'165')
Lecture.create(name: '미술과 상상력', major_id:'20', professor_id:'99')
Lecture.create(name: '인문학 글쓰기', major_id:'20', professor_id:'7')
Lecture.create(name: '인물로본중국', major_id:'20', professor_id:'19')
Lecture.create(name: '특강1:영문번역의기초', major_id:'20', professor_id:'209')
Lecture.create(name: 'TED Presentation', major_id:'20', professor_id:'58')
Lecture.create(name: 'Activity-based Learning and Strategic Competence', major_id:'20', professor_id:'215')
Lecture.create(name: '컴퓨터활용', major_id:'21', professor_id:'150')
Lecture.create(name: '컴퓨터활용', major_id:'21', professor_id:'150')
Lecture.create(name: '대학수학', major_id:'21', professor_id:'156')
Lecture.create(name: '홈페이지제작', major_id:'21', professor_id:'177')
Lecture.create(name: '컴퓨터그래픽 활용', major_id:'21', professor_id:'175')
Lecture.create(name: '생활과 과학', major_id:'21', professor_id:'21')
Lecture.create(name: '확률과 통계', major_id:'21', professor_id:'73')
Lecture.create(name: '확률과 통계', major_id:'21', professor_id:'73')
Lecture.create(name: '과학과 종교', major_id:'21', professor_id:'11')
Lecture.create(name: 'SNS 활용', major_id:'21', professor_id:'69')
Lecture.create(name: 'IT직업의 세계', major_id:'21', professor_id:'206')
Lecture.create(name: '공업수학', major_id:'21', professor_id:'79')
Lecture.create(name: '공업수학II', major_id:'21', professor_id:'156')
Lecture.create(name: '과학적사고와상상력', major_id:'21', professor_id:'113')
Lecture.create(name: '인터넷과 네트워크', major_id:'21', professor_id:'61')
Lecture.create(name: '진로와 직업의 세계 II', major_id:'22', professor_id:'132')
Lecture.create(name: '취업전략 및 역량강화 II', major_id:'22', professor_id:'125')
Lecture.create(name: '사회진출세미나II', major_id:'22', professor_id:'88')
Lecture.create(name: '사회진출세미나 IV', major_id:'22', professor_id:'88')
Lecture.create(name: '창업과기업가정신II', major_id:'22', professor_id:'2')
Lecture.create(name: '창업과디자인씽킹II', major_id:'22', professor_id:'2')
Lecture.create(name: '스마트업프레젠테이션전략 II', major_id:'22', professor_id:'186')




Professor.create(name: '강인선', dis: '1')
Professor.create(name: '강지훈', dis: '1')
Professor.create(name: '경제희', dis: '1')
Professor.create(name: '고경대', dis: '1')
Professor.create(name: '고병헌', dis: '1')
Professor.create(name: '교목실', dis: '1')
Professor.create(name: '권순엽', dis: '1')
Professor.create(name: '권용현', dis: '1')
Professor.create(name: '권혁태', dis: '1')
Professor.create(name: '김공회', dis: '1')
Professor.create(name: '김기석', dis: '1')
Professor.create(name: '김남석', dis: '1')
Professor.create(name: '김대우', dis: '1')
Professor.create(name: '김덕봉', dis: '1')
Professor.create(name: '김동준', dis: '1')
Professor.create(name: '김동춘', dis: '1')
Professor.create(name: '김명준', dis: '1')
Professor.create(name: '김명하', dis: '1')
Professor.create(name: '김명호', dis: '1')
Professor.create(name: '김미란', dis: '1')
Professor.create(name: '김병수', dis: '1')
Professor.create(name: '김서중', dis: '1')
Professor.create(name: '김선형', dis: '1')
Professor.create(name: '김선화', dis: '1')
Professor.create(name: '김성규', dis: '1')
Professor.create(name: '김성기', dis: '1')
Professor.create(name: '김성찬', dis: '1')
Professor.create(name: '김성호', dis: '1')
Professor.create(name: '김수정', dis: '1')
Professor.create(name: '김순남', dis: '1')
Professor.create(name: '김신식', dis: '1')
Professor.create(name: '김양태', dis: '1')
Professor.create(name: '김엘리', dis: '1')
Professor.create(name: '김연아', dis: '1')
Professor.create(name: '김영희', dis: '1')
Professor.create(name: '김용득', dis: '1')
Professor.create(name: '김용찬', dis: '1')
Professor.create(name: '김용한', dis: '1')
Professor.create(name: '김용호', dis: '1')
Professor.create(name: '김원식', dis: '1')
Professor.create(name: '김유순', dis: '1')
Professor.create(name: '김은규', dis: '1')
Professor.create(name: '김은영', dis: '1')
Professor.create(name: '김재명', dis: '1')
Professor.create(name: '김재민', dis: '1')
Professor.create(name: '김정기', dis: '1')
Professor.create(name: '김정주', dis: '1')
Professor.create(name: '김종훈', dis: '1')
Professor.create(name: '김주연', dis: '1')
Professor.create(name: '김창남', dis: '1')
Professor.create(name: '김창진', dis: '1')
Professor.create(name: '김태우', dis: '1')
Professor.create(name: '김태욱', dis: '1')
Professor.create(name: '김택규', dis: '1')
Professor.create(name: '김학수', dis: '1')
Professor.create(name: '김한나', dis: '1')
Professor.create(name: '김형미', dis: '1')
Professor.create(name: '김혜인', dis: '1')
Professor.create(name: '김혜진', dis: '1')
Professor.create(name: '김호영', dis: '1')
Professor.create(name: '김홍열', dis: '1')
Professor.create(name: '김활신', dis: '1')
Professor.create(name: '김희정', dis: '1')
Professor.create(name: '남일성', dis: '2')
Professor.create(name: '노은하', dis: '2')
Professor.create(name: '마상우', dis: '5')
Professor.create(name: '문성현', dis: '5')
Professor.create(name: '박경태', dis: '6')
Professor.create(name: '박경호', dis: '6')
Professor.create(name: '박미숙', dis: '6')
Professor.create(name: '박미정', dis: '6')
Professor.create(name: '박병상', dis: '6')
Professor.create(name: '박상선', dis: '6')
Professor.create(name: '박상필', dis: '6')
Professor.create(name: '박승호', dis: '6')
Professor.create(name: '박윤규', dis: '6')
Professor.create(name: '박은홍', dis: '6')
Professor.create(name: '박은희', dis: '6')
Professor.create(name: '박정식', dis: '6')
Professor.create(name: '박정환', dis: '6')
Professor.create(name: '박태식', dis: '6')
Professor.create(name: '박태영', dis: '6')
Professor.create(name: '박현수', dis: '6')
Professor.create(name: '배성인', dis: '6')
Professor.create(name: '백원담', dis: '6')
Professor.create(name: '백정숙', dis: '6')
Professor.create(name: '사회교육원', dis: '7')
Professor.create(name: '사회진출실', dis: '7')
Professor.create(name: '상종열', dis: '7')
Professor.create(name: '서진선', dis: '7')
Professor.create(name: '서진환', dis: '7')
Professor.create(name: '손광식', dis: '7')
Professor.create(name: '신익상', dis: '7')
Professor.create(name: '신정완', dis: '7')
Professor.create(name: '신주백', dis: '7')
Professor.create(name: '신항우', dis: '7')
Professor.create(name: '신효진', dis: '7')
Professor.create(name: '안진걸', dis: '8')
Professor.create(name: '안현배', dis: '8')
Professor.create(name: '안효상', dis: '8')
Professor.create(name: '양권석', dis: '8')
Professor.create(name: '양만호', dis: '8')
Professor.create(name: '양재영', dis: '8')
Professor.create(name: '엄순천', dis: '8')
Professor.create(name: '연광석', dis: '8')
Professor.create(name: '연희승', dis: '8')
Professor.create(name: '염준규', dis: '8')
Professor.create(name: '염찬희', dis: '8')
Professor.create(name: '오명숙', dis: '8')
Professor.create(name: '오세풍', dis: '8')
Professor.create(name: '오유석', dis: '8')
Professor.create(name: '요코야마 나오코', dis: '8')
Professor.create(name: '원종우', dis: '8')
Professor.create(name: '원종호', dis: '8')
Professor.create(name: '유상신', dis: '8')
Professor.create(name: '유승호', dis: '8')
Professor.create(name: '유철규', dis: '8')
Professor.create(name: '윤목', dis: '8')
Professor.create(name: '이계우', dis: '8')
Professor.create(name: '이기형', dis: '8')
Professor.create(name: '이남석', dis: '8')
Professor.create(name: '이남주', dis: '8')
Professor.create(name: '이남호', dis: '8')
Professor.create(name: '이명춘', dis: '8')
Professor.create(name: '이미혜', dis: '8')
Professor.create(name: '이복실', dis: '8')
Professor.create(name: '이봉범', dis: '8')
Professor.create(name: '이상윤', dis: '8')
Professor.create(name: '이상철', dis: '8')
Professor.create(name: '이상훈', dis: '8')
Professor.create(name: '이숙진', dis: '8')
Professor.create(name: '이승이', dis: '8')
Professor.create(name: '이승진', dis: '8')
Professor.create(name: '이승희', dis: '8')
Professor.create(name: '이안젤라', dis: '8')
Professor.create(name: '이영아', dis: '8')
Professor.create(name: '이영환', dis: '8')
Professor.create(name: '이예나', dis: '8')
Professor.create(name: '이웅', dis: '8')
Professor.create(name: '이원석', dis: '8')
Professor.create(name: '이원정', dis: '8')
Professor.create(name: '이윤구', dis: '8')
Professor.create(name: '이제이', dis: '8')
Professor.create(name: '이종구', dis: '8')
Professor.create(name: '이종현', dis: '8')
Professor.create(name: '이주룡', dis: '8')
Professor.create(name: '이주엽', dis: '8')
Professor.create(name: '이준희', dis: '8')
Professor.create(name: '이하규', dis: '8')
Professor.create(name: '이해신', dis: '8')
Professor.create(name: '임경순', dis: '8')
Professor.create(name: '임규찬', dis: '8')
Professor.create(name: '임성윤', dis: '8')
Professor.create(name: '임창규', dis: '8')
Professor.create(name: '임충규', dis: '8')
Professor.create(name: '임형', dis: '8')
Professor.create(name: '장명숙', dis: '9')
Professor.create(name: '장수철', dis: '9')
Professor.create(name: '장승권', dis: '9')
Professor.create(name: '장엽', dis: '9')
Professor.create(name: '장영석', dis: '9')
Professor.create(name: '장진웅', dis: '9')
Professor.create(name: '장화경', dis: '9')
Professor.create(name: '장희숙', dis: '9')
Professor.create(name: '전성원', dis: '9')
Professor.create(name: '정미애', dis: '9')
Professor.create(name: '정병일', dis: '9')
Professor.create(name: '정연보', dis: '9')
Professor.create(name: '정연식', dis: '9')
Professor.create(name: '정영희', dis: '9')
Professor.create(name: '정용권', dis: '9')
Professor.create(name: '정원오', dis: '9')
Professor.create(name: '정인철', dis: '9')
Professor.create(name: '정지연', dis: '9')
Professor.create(name: '정진철', dis: '9')
Professor.create(name: '정해구', dis: '9')
Professor.create(name: '정희경', dis: '9')
Professor.create(name: '조남경', dis: '9')
Professor.create(name: '조미혜', dis: '9')
Professor.create(name: '조병은', dis: '9')
Professor.create(name: '조옥희', dis: '9')
Professor.create(name: '조은기', dis: '9')
Professor.create(name: '조정위', dis: '9')
Professor.create(name: '조효제', dis: '9')
Professor.create(name: '주하영', dis: '9')
Professor.create(name: '지효선', dis: '9')
Professor.create(name: '진영종', dis: '9')
Professor.create(name: '진정석', dis: '9')
Professor.create(name: '채기화', dis: '10')
Professor.create(name: '채수진', dis: '10')
Professor.create(name: '최경옥', dis: '10')
Professor.create(name: '최동호', dis: '10')
Professor.create(name: '최민희', dis: '10')
Professor.create(name: '최병구', dis: '10')
Professor.create(name: '최수일', dis: '10')
Professor.create(name: '최우석', dis: '10')
Professor.create(name: '최은경', dis: '10')
Professor.create(name: '최은주', dis: '10')
Professor.create(name: '최인숙', dis: '10')
Professor.create(name: '최진봉', dis: '10')
Professor.create(name: '탁현민', dis: '12')
Professor.create(name: '하남석', dis: '14')
Professor.create(name: '한긍수', dis: '14')
Professor.create(name: '한진일', dis: '14')
Professor.create(name: '한홍구', dis: '14')
Professor.create(name: '함병현', dis: '14')
Professor.create(name: '허성우', dis: '14')
Professor.create(name: '호중훈', dis: '14')
Professor.create(name: '홍영경', dis: '14')
Professor.create(name: '홍은지', dis: '14')
Professor.create(name: '홍정수', dis: '14')
Professor.create(name: '홍준철', dis: '14')
Professor.create(name: '황선길', dis: '14')
Professor.create(name: 'Calano', dis: '15')
Professor.create(name: 'Steve', dis: '15')
Professor.create(name: '(미정)', dis: '16')