# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Major.create(name: '경영학부')
Major.create(name: '글로컬IT학과')
Major.create(name: '디지털컨텐츠학과')
Major.create(name: '사회과학부')
Major.create(name: '사과부_사회학')
Major.create(name: '사과부_경제학')
Major.create(name: '사과부_정치학')
Major.create(name: '사회복지학과')
Major.create(name: '소프트웨어공학과')
Major.create(name: '신문방송학과')
Major.create(name: '신학과')
Major.create(name: '영어학과')
Major.create(name: '일어일본학과')
Major.create(name: '정보통신공학과')
Major.create(name: '중어중국학과')
Major.create(name: '컴퓨터공학과')
Major.create(name: '교양필수')
Major.create(name: '채플')
Major.create(name: '교양사회')
Major.create(name: '교양인문')
Major.create(name: '교양자연')
Major.create(name: '사회진출실')

Lecture.create(name: '회계학1 (회계학원론1)', major_id:'1', professor_id:'139')
Lecture.create(name: '경영통계(2)', major_id:'1', professor_id:'138')
Lecture.create(name: '경영통계(2,3,4)', major_id:'1', professor_id:'138')
Lecture.create(name: '경영조직론과 리더십', major_id:'1', professor_id:'15')
Lecture.create(name: '경영정보학 (경영정보학개론/전자상거래원론) ', major_id:'1', professor_id:'109')
Lecture.create(name: '중급회계', major_id:'1', professor_id:'22')
Lecture.create(name: '시스템분석 및 설계 (시스템분석 및 설계/전자상거래구축)', major_id:'1', professor_id:'53')
Lecture.create(name: '마케팅조사방법론(3)', major_id:'1', professor_id:'88')
Lecture.create(name: '마케팅조사방법론(3,4)', major_id:'1', professor_id:'88')
Lecture.create(name: '글로컬 입문', major_id:'2', professor_id:'32')
Lecture.create(name: '지역IT탐방(01)', major_id:'2', professor_id:'14')
Lecture.create(name: '지역IT탐방(02)', major_id:'2', professor_id:'14')
Lecture.create(name: '문제해결기초', major_id:'2', professor_id:'14')
Lecture.create(name: 'C 프로그래밍', major_id:'2', professor_id:'14')
Lecture.create(name: '객체지향프로그래밍', major_id:'2', professor_id:'32')
Lecture.create(name: '데이터베이스프로그래밍', major_id:'2', professor_id:'32')
Lecture.create(name: '세미나4(01)', major_id:'2', professor_id:'14')
Lecture.create(name: '세미나4(02)', major_id:'2', professor_id:'14')
Lecture.create(name: '실무프로젝트', major_id:'2', professor_id:'32')
Lecture.create(name: '운영체제론', major_id:'2', professor_id:'14')
Lecture.create(name: '해부학과 표현', major_id:'3', professor_id:'13')
Lecture.create(name: '게임제작', major_id:'3', professor_id:'125')
Lecture.create(name: '3D 캐릭터 애니메이션', major_id:'3', professor_id:'127')
Lecture.create(name: '디지털기초조형', major_id:'3', professor_id:'13')
Lecture.create(name: '3D모델링(01)', major_id:'3', professor_id:'96')
Lecture.create(name: '3D모델링(02)', major_id:'3', professor_id:'96')
Lecture.create(name: '포트폴리오 I(01)', major_id:'3', professor_id:'13')
Lecture.create(name: '포트폴리오 I(02)', major_id:'3', professor_id:'96')
Lecture.create(name: '전공세미나 II(01)', major_id:'3', professor_id:'13')
Lecture.create(name: '전공세미나 II(02)', major_id:'3', professor_id:'96')
Lecture.create(name: '다큐멘터리 기획 제작', major_id:'3', professor_id:'142')
Lecture.create(name: '글로벌 콘텐츠 비즈니스', major_id:'3', professor_id:'67')
Lecture.create(name: '경제학개론(01)', major_id:'4', professor_id:'79')
Lecture.create(name: '경제학개론(02)', major_id:'4', professor_id:'79')
Lecture.create(name: '자본주의의 이해', major_id:'4', professor_id:'79')
Lecture.create(name: '사회학세미나 I', major_id:'5', professor_id:'128')
Lecture.create(name: '경제학세미나 I', major_id:'6', professor_id:'79')
Lecture.create(name: '정치학세미나 I', major_id:'7', professor_id:'120')
Lecture.create(name: '인간행동과사회환경(01)', major_id:'8', professor_id:'63')
Lecture.create(name: '인간행동과사회환경(02)', major_id:'8', professor_id:'134')
Lecture.create(name: '사회복지조사론', major_id:'8', professor_id:'43')
Lecture.create(name: '사회복지법제', major_id:'8', professor_id:'93')
Lecture.create(name: '사회복지행정론', major_id:'8', professor_id:'28')
Lecture.create(name: '사회복지정책론', major_id:'8', professor_id:'93')
Lecture.create(name: '지역사회복지론', major_id:'8', professor_id:'43')
Lecture.create(name: '사회복지실천기술론(01)', major_id:'8', professor_id:'112')
Lecture.create(name: '사회복지실천기술론(02)', major_id:'8', professor_id:'112')
Lecture.create(name: '사회복지현장실습 I(01)', major_id:'8', professor_id:'43')
Lecture.create(name: '사회복지현장실습 I(02)', major_id:'8', professor_id:'123')
Lecture.create(name: '세미나지도4(01)', major_id:'8', professor_id:'63')
Lecture.create(name: '세미나지도4(02)', major_id:'8', professor_id:'28')
Lecture.create(name: '운영체제론', major_id:'9', professor_id:'44')
Lecture.create(name: 'C프로그래밍Ⅱ(01)', major_id:'9', professor_id:'148')
Lecture.create(name: 'C프로그래밍Ⅱ(02)', major_id:'9', professor_id:'77')
Lecture.create(name: '웹페이지구축Ⅰ', major_id:'9', professor_id:'115')
Lecture.create(name: '자료구조론(01)', major_id:'9', professor_id:'45')
Lecture.create(name: '자료구조론(02)', major_id:'9', professor_id:'45')
Lecture.create(name: '과정지도2', major_id:'9', professor_id:'148')
Lecture.create(name: '과정지도4', major_id:'9', professor_id:'148')
Lecture.create(name: '과정지도6', major_id:'9', professor_id:'91')
Lecture.create(name: '미디어연구방법', major_id:'10', professor_id:'126')
Lecture.create(name: '스피치커뮤니케이션(01)', major_id:'10', professor_id:'140')
Lecture.create(name: '스피치커뮤니케이션(02)', major_id:'10', professor_id:'140')
Lecture.create(name: '졸업세미나(01)', major_id:'10', professor_id:'126')
Lecture.create(name: '졸업세미나(02)', major_id:'10', professor_id:'19')
Lecture.create(name: '기사작성과 편집Ⅰ', major_id:'10', professor_id:'23')
Lecture.create(name: '매스컴 영어(01)', major_id:'10', professor_id:'140')
Lecture.create(name: '매스컴 영어(02)', major_id:'10', professor_id:'140')
Lecture.create(name: '논문지도I', major_id:'11', professor_id:'70')
Lecture.create(name: '논문지도Ⅱ', major_id:'11', professor_id:'11')
Lecture.create(name: '성서의 이해', major_id:'11', professor_id:'56')
Lecture.create(name: '구약성서의 이해', major_id:'11', professor_id:'31')
Lecture.create(name: '미국문학개론', major_id:'12', professor_id:'131')
Lecture.create(name: '영작문Ⅱ(01)', major_id:'12', professor_id:'40')
Lecture.create(name: '영작문Ⅱ(02)', major_id:'12', professor_id:'40')
Lecture.create(name: '영어독서지도', major_id:'12', professor_id:'21')
Lecture.create(name: '영어문장이해II', major_id:'12', professor_id:'21')
Lecture.create(name: '영미문학: 자연과 인간', major_id:'12', professor_id:'124')
Lecture.create(name: '영미문학과 여성', major_id:'12', professor_id:'124')
Lecture.create(name: '미국문화와 사회', major_id:'12', professor_id:'131')
Lecture.create(name: '영어다독Ⅱ(01)', major_id:'12', professor_id:'8')
Lecture.create(name: '영어다독Ⅱ(02)', major_id:'12', professor_id:'124')
Lecture.create(name: '실용영문법 II', major_id:'12', professor_id:'8')
Lecture.create(name: '언어와 커뮤니케이션 2', major_id:'12', professor_id:'8')
Lecture.create(name: '영어발달사', major_id:'12', professor_id:'21')
Lecture.create(name: '일본학세미나', major_id:'13', professor_id:'3')
Lecture.create(name: 'C프로그래밍II(01)', major_id:'14', professor_id:'101')
Lecture.create(name: 'C프로그래밍II(02)', major_id:'14', professor_id:'101')
Lecture.create(name: '데이터통신', major_id:'14', professor_id:'36')
Lecture.create(name: '전공지도II(01)', major_id:'14', professor_id:'36')
Lecture.create(name: '전공지도II(02)', major_id:'14', professor_id:'55')
Lecture.create(name: '전공지도II(03)', major_id:'14', professor_id:'118')
Lecture.create(name: '객체지향시스템', major_id:'14', professor_id:'20')
Lecture.create(name: '통신개발프로젝트I(01)', major_id:'14', professor_id:'55')
Lecture.create(name: '통신개발프로젝트I(02)', major_id:'14', professor_id:'118')
Lecture.create(name: '졸업지도', major_id:'14', professor_id:'55')
Lecture.create(name: '중국사회조사연습', major_id:'15', professor_id:'110')
Lecture.create(name: '졸업논문지도', major_id:'15', professor_id:'110')
Lecture.create(name: '중국학개론', major_id:'15', professor_id:'82')
Lecture.create(name: '한문연습', major_id:'15', professor_id:'59')
Lecture.create(name: '세미나II(01)', major_id:'15', professor_id:'110')
Lecture.create(name: '세미나II(02)', major_id:'15', professor_id:'110')
Lecture.create(name: '세미나II(03)', major_id:'15', professor_id:'110')
Lecture.create(name: '중국의 경제정책', major_id:'15', professor_id:'82')
Lecture.create(name: '졸업지도', major_id:'15', professor_id:'59')
Lecture.create(name: '컴퓨터구조', major_id:'16', professor_id:'20')
Lecture.create(name: 'C프로그래밍II', major_id:'16', professor_id:'106')
Lecture.create(name: '운영체제 ', major_id:'16', professor_id:'20')
Lecture.create(name: '신호 및 시스템', major_id:'16', professor_id:'38')
Lecture.create(name: '컴퓨터네트워크', major_id:'16', professor_id:'114')
Lecture.create(name: '윈도우즈프로그래밍', major_id:'16', professor_id:'38')
Lecture.create(name: '멀티미디어처리프로젝트', major_id:'16', professor_id:'38')
Lecture.create(name: '과정지도4', major_id:'16', professor_id:'38')
Lecture.create(name: '과정지도6', major_id:'16', professor_id:'114')
Lecture.create(name: '그래픽스프로젝트', major_id:'16', professor_id:'106')
Lecture.create(name: '졸업지도 2', major_id:'16', professor_id:'106')
Lecture.create(name: 'C프로그래밍실습II', major_id:'16', professor_id:'106')
Lecture.create(name: '말과글(01)', major_id:'17', professor_id:'64')
Lecture.create(name: '말과글(02)', major_id:'17', professor_id:'86')
Lecture.create(name: '말과글(03)', major_id:'17', professor_id:'92')
Lecture.create(name: '말과글(04)', major_id:'17', professor_id:'137')
Lecture.create(name: '말과글(05)', major_id:'17', professor_id:'143')
Lecture.create(name: '말과글(06)', major_id:'17', professor_id:'64')
Lecture.create(name: '말과글(07)', major_id:'17', professor_id:'86')
Lecture.create(name: '말과글(08)', major_id:'17', professor_id:'92')
Lecture.create(name: '말과글(09)', major_id:'17', professor_id:'137')
Lecture.create(name: '말과글(10)', major_id:'17', professor_id:'27')
Lecture.create(name: '말과글(11)', major_id:'17', professor_id:'64')
Lecture.create(name: '말과글(12)', major_id:'17', professor_id:'86')
Lecture.create(name: '말과글(13)', major_id:'17', professor_id:'92')
Lecture.create(name: '말과글(14)', major_id:'17', professor_id:'137')
Lecture.create(name: '말과글(15)', major_id:'17', professor_id:'27')
Lecture.create(name: '말과글(16)', major_id:'17', professor_id:'103')
Lecture.create(name: '말과글(17)', major_id:'17', professor_id:'78')
Lecture.create(name: '말과글(18)', major_id:'17', professor_id:'132')
Lecture.create(name: '대학생활세미나 II (01)', major_id:'17', professor_id:'13')
Lecture.create(name: '대학생활세미나 II (02)', major_id:'17', professor_id:'96')
Lecture.create(name: '대학생활세미나 II (03)', major_id:'17', professor_id:'38')
Lecture.create(name: '대학생활세미나 II (04)', major_id:'17', professor_id:'114')
Lecture.create(name: '대학생활세미나 II (05)', major_id:'17', professor_id:'77')
Lecture.create(name: '대학생활세미나 II (06)', major_id:'17', professor_id:'107')
Lecture.create(name: '대학생활세미나 II (07)', major_id:'17', professor_id:'36')
Lecture.create(name: '대학생활세미나 II (08)', major_id:'17', professor_id:'118')
Lecture.create(name: '대학생활세미나 II (09)', major_id:'17', professor_id:'32')
Lecture.create(name: '대학생활세미나 II (10)', major_id:'17', professor_id:'32')
Lecture.create(name: '대학생활세미나 II (11)', major_id:'17', professor_id:'21')
Lecture.create(name: '대학생활세미나 II (12)', major_id:'17', professor_id:'8')
Lecture.create(name: '대학생활세미나 II (13)', major_id:'17', professor_id:'111')
Lecture.create(name: '대학생활세미나 II (14)', major_id:'17', professor_id:'9')
Lecture.create(name: '대학생활세미나 II (15)', major_id:'17', professor_id:'87')
Lecture.create(name: '대학생활세미나 II (18)', major_id:'17', professor_id:'11')
Lecture.create(name: '대학생활세미나 II (19)', major_id:'17', professor_id:'35')
Lecture.create(name: '대학생활세미나 II (20)', major_id:'17', professor_id:'98')
Lecture.create(name: '대학생활세미나 II (21)', major_id:'17', professor_id:'120')
Lecture.create(name: '대학생활세미나 II (24)', major_id:'17', professor_id:'54')
Lecture.create(name: '대학생활세미나 II (25)', major_id:'17', professor_id:'65')
Lecture.create(name: '대학생활세미나 II (26)', major_id:'17', professor_id:'128')
Lecture.create(name: '대학생활세미나 II (27)', major_id:'17', professor_id:'117')
Lecture.create(name: '대학생활세미나 II (28)', major_id:'17', professor_id:'93')
Lecture.create(name: '대학생활세미나 II (29)', major_id:'17', professor_id:'122')
Lecture.create(name: '대학생활세미나 II (30)', major_id:'17', professor_id:'110')
Lecture.create(name: '대학생활세미나 II (32)', major_id:'17', professor_id:'51')
Lecture.create(name: '대학생활세미나 II (33)', major_id:'17', professor_id:'140')
Lecture.create(name: '대학생활세미나 II (34)', major_id:'17', professor_id:'56')
Lecture.create(name: '대학생활세미나 II (35)', major_id:'17', professor_id:'82')
Lecture.create(name: '시네마채플', major_id:'18', professor_id:'56')
Lecture.create(name: '세계의 종교', major_id:'18', professor_id:'6')
Lecture.create(name: '애니어그램', major_id:'18', professor_id:'83')
Lecture.create(name: '생활과 영성', major_id:'18', professor_id:'12')
Lecture.create(name: '불완전한 존재로 살아가기', major_id:'18', professor_id:'33')
Lecture.create(name: '언저리에서 만나는 종교', major_id:'18', professor_id:'33')
Lecture.create(name: '교회음악', major_id:'18', professor_id:'57')
Lecture.create(name: '표현예술치료', major_id:'18', professor_id:'97')
Lecture.create(name: '경배와 찬양', major_id:'18', professor_id:'6')
Lecture.create(name: '명상', major_id:'18', professor_id:'99')
Lecture.create(name: '종교간대화의 영성', major_id:'18', professor_id:'80')
Lecture.create(name: '종교학 특강', major_id:'18', professor_id:'99')
Lecture.create(name: '한국의 종교', major_id:'18', professor_id:'6')
Lecture.create(name: '스트레스 관리', major_id:'18', professor_id:'99')
Lecture.create(name: '스님과 함께 하는 채플', major_id:'18', professor_id:'6')
Lecture.create(name: '성공회 감사성찬례', major_id:'18', professor_id:'37')
Lecture.create(name: '연극채플', major_id:'18', professor_id:'108')
Lecture.create(name: '신학과 채플', major_id:'18', professor_id:'11')
Lecture.create(name: 'MBSR', major_id:'18', professor_id:'149')
Lecture.create(name: '성서와 함께', major_id:'18', professor_id:'6')
Lecture.create(name: '인권과평화', major_id:'19', professor_id:'26')
Lecture.create(name: '영상시대의이해', major_id:'19', professor_id:'25')
Lecture.create(name: '사회학개론', major_id:'19', professor_id:'46')
Lecture.create(name: '매스컴과 현대사회', major_id:'19', professor_id:'35')
Lecture.create(name: '경영학원론', major_id:'19', professor_id:'87')
Lecture.create(name: '아시아사회와 문화', major_id:'19', professor_id:'54')
Lecture.create(name: '환경과 인간', major_id:'19', professor_id:'50')
Lecture.create(name: '대중음악의이해', major_id:'19', professor_id:'100')
Lecture.create(name: '노래로 보는 한국사회', major_id:'19', professor_id:'81')
Lecture.create(name: '경제학개론', major_id:'19', professor_id:'94')
Lecture.create(name: '정치경제학', major_id:'19', professor_id:'10')
Lecture.create(name: '협동조합과 대안사회', major_id:'19', professor_id:'72')
Lecture.create(name: '정신건강', major_id:'19', professor_id:'133')
Lecture.create(name: '성 사랑 결혼', major_id:'19', professor_id:'24')
Lecture.create(name: '법학통론', major_id:'19', professor_id:'84')
Lecture.create(name: '살아있는 자연', major_id:'19', professor_id:'30')
Lecture.create(name: '여성과 인권', major_id:'19', professor_id:'89')
Lecture.create(name: '한국노동운동의 역사와 이론', major_id:'19', professor_id:'52')
Lecture.create(name: '팀창업입문', major_id:'19', professor_id:'109')
Lecture.create(name: '팀창업입문', major_id:'19', professor_id:'76')
Lecture.create(name: '팀창업입문', major_id:'19', professor_id:'42')
Lecture.create(name: '특강2:세계 기업의 역사', major_id:'19', professor_id:'105')
Lecture.create(name: '특강3:인문성과 시민성에 관한 세미나', major_id:'19', professor_id:'62')
Lecture.create(name: '여성운동: 인식과 실천', major_id:'19', professor_id:'146')
Lecture.create(name: '지역재단과 사회공헌', major_id:'19', professor_id:'')
Lecture.create(name: '세상읽기와 글쓰기', major_id:'20', professor_id:'103')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'1')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'49')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'49')
Lecture.create(name: '기초영어II', major_id:'20', professor_id:'95')
Lecture.create(name: '더불어숲 인문학-청춘, 삶, 문학', major_id:'20', professor_id:'104')
Lecture.create(name: '더불어숲 인문학-삶을 위한 공부', major_id:'20', professor_id:'5')
Lecture.create(name: '더불어숲 인문학-역사 속을 걷다.', major_id:'20', professor_id:'144')
Lecture.create(name: '더불어숲 인문학-문학으로 읽는 인권', major_id:'20', professor_id:'131')
Lecture.create(name: '교양일본어 1', major_id:'20', professor_id:'48')
Lecture.create(name: '교양일본어 1', major_id:'20', professor_id:'17')
Lecture.create(name: '언어의 이해', major_id:'20', professor_id:'3')
Lecture.create(name: '서양사의 이해', major_id:'20', professor_id:'69')
Lecture.create(name: '교양중국어 초급', major_id:'20', professor_id:'141')
Lecture.create(name: '실용영어(TOEIC) I', major_id:'20', professor_id:'74')
Lecture.create(name: '역사속의 한국과 미국', major_id:'20', professor_id:'29')
Lecture.create(name: '교양합창II', major_id:'20', professor_id:'150')
Lecture.create(name: '한국소설산책', major_id:'20', professor_id:'58')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'1')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'1')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'1')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'40')
Lecture.create(name: '영어회화II', major_id:'20', professor_id:'2')
Lecture.create(name: '서양문학의 흐름', major_id:'20', professor_id:'124')
Lecture.create(name: '논리와 비판적 사고', major_id:'20', professor_id:'135')
Lecture.create(name: '문학과 영상', major_id:'20', professor_id:'78')
Lecture.create(name: '한국 도시공간의 역사와 문화경험', major_id:'20', professor_id:'66')
Lecture.create(name: '교양시사영어II', major_id:'20', professor_id:'21')
Lecture.create(name: '한국현대사', major_id:'20', professor_id:'144')
Lecture.create(name: '문화유산탐방', major_id:'20', professor_id:'73')
Lecture.create(name: '한국연극의 이해', major_id:'20', professor_id:'108')
Lecture.create(name: '시각문화와 예술', major_id:'20', professor_id:'129')
Lecture.create(name: '한국어II', major_id:'20', professor_id:'60')
Lecture.create(name: '종교와 예술', major_id:'20', professor_id:'34')
Lecture.create(name: '교양러시아어 I', major_id:'20', professor_id:'71')
Lecture.create(name: '사진으로 보는 한국근현대사', major_id:'20', professor_id:'66')
Lecture.create(name: '실용영어(TOEIC) 2', major_id:'20', professor_id:'74')
Lecture.create(name: '상상력과 창의력 -기획과 글쓰기', major_id:'20', professor_id:'136')
Lecture.create(name: '온라인 게임과 종교적 상징', major_id:'20', professor_id:'39')
Lecture.create(name: '한국어 교육방법론', major_id:'20', professor_id:'58')
Lecture.create(name: 'Fun English II', major_id:'20', professor_id:'40')
Lecture.create(name: '기초영문법 II', major_id:'20', professor_id:'21')
Lecture.create(name: '기초영문법 II', major_id:'20', professor_id:'116')
Lecture.create(name: '문예창작과 감상 II', major_id:'20', professor_id:'132')
Lecture.create(name: '문학비평의 방법과 실제', major_id:'20', professor_id:'104')
Lecture.create(name: 'LIfe Talk', major_id:'20', professor_id:'40')
Lecture.create(name: '인터넷과 글쓰기', major_id:'20', professor_id:'143')
Lecture.create(name: '한국인과 고전의 세계', major_id:'20', professor_id:'104')
Lecture.create(name: 'Business english', major_id:'20', professor_id:'1')
Lecture.create(name: 'English Speech II', major_id:'20', professor_id:'2')
Lecture.create(name: 'Intercultural Communication I', major_id:'20', professor_id:'1')
Lecture.create(name: 'Internet English', major_id:'20', professor_id:'2')
Lecture.create(name: 'Global Career and Leadership II', major_id:'20', professor_id:'2')
Lecture.create(name: '책의문화사', major_id:'20', professor_id:'113')
Lecture.create(name: '미술과 상상력', major_id:'20', professor_id:'68')
Lecture.create(name: '인문학 글쓰기', major_id:'20', professor_id:'7')
Lecture.create(name: '인물로본중국', major_id:'20', professor_id:'16')
Lecture.create(name: '특강1:영문번역의기초', major_id:'20', professor_id:'147')
Lecture.create(name: 'TED Presentation', major_id:'20', professor_id:'40')
Lecture.create(name: 'Activity-based Learning and Strategic Competence', major_id:'20', professor_id:'2')
Lecture.create(name: '컴퓨터활용', major_id:'21', professor_id:'102')
Lecture.create(name: '컴퓨터활용', major_id:'21', professor_id:'102')
Lecture.create(name: '대학수학', major_id:'21', professor_id:'107')
Lecture.create(name: '홈페이지제작', major_id:'21', professor_id:'121')
Lecture.create(name: '컴퓨터그래픽 활용', major_id:'21', professor_id:'119')
Lecture.create(name: '생활과 과학', major_id:'21', professor_id:'18')
Lecture.create(name: '확률과 통계', major_id:'21', professor_id:'51')
Lecture.create(name: '확률과 통계', major_id:'21', professor_id:'51')
Lecture.create(name: '과학과 종교', major_id:'21', professor_id:'11')
Lecture.create(name: 'SNS 활용', major_id:'21', professor_id:'47')
Lecture.create(name: 'IT직업의 세계', major_id:'21', professor_id:'145')
Lecture.create(name: '공업수학', major_id:'21', professor_id:'55')
Lecture.create(name: '공업수학II', major_id:'21', professor_id:'107')
Lecture.create(name: '과학적사고와상상력', major_id:'21', professor_id:'75')
Lecture.create(name: '인터넷과 네트워크', major_id:'21', professor_id:'41')
Lecture.create(name: '진로와 직업의 세계 II', major_id:'22', professor_id:'90')
Lecture.create(name: '취업전략 및 역량강화 II', major_id:'22', professor_id:'85')
Lecture.create(name: '사회진출세미나II', major_id:'22', professor_id:'61')
Lecture.create(name: '사회진출세미나 IV', major_id:'22', professor_id:'61')
Lecture.create(name: '창업과기업가정신II', major_id:'22', professor_id:'4')
Lecture.create(name: '창업과디자인씽킹II', major_id:'22', professor_id:'4')
Lecture.create(name: '스마트업프레젠테이션전략 II', major_id:'22', professor_id:'130')


Professor.create(name: 'Calano')
Professor.create(name: 'Steve')
Professor.create(name: '강인선')
Professor.create(name: '강지훈')
Professor.create(name: '고병헌')
Professor.create(name: '교목실')
Professor.create(name: '권순엽')
Professor.create(name: '권용현')
Professor.create(name: '권혁태')
Professor.create(name: '김공회')
Professor.create(name: '김기석')
Professor.create(name: '김남석')
Professor.create(name: '김대우')
Professor.create(name: '김덕봉')
Professor.create(name: '김동준')
Professor.create(name: '김명호')
Professor.create(name: '김미란')
Professor.create(name: '김병수')
Professor.create(name: '김서중')
Professor.create(name: '김선형')
Professor.create(name: '김성찬')
Professor.create(name: '김성호')
Professor.create(name: '김수정')
Professor.create(name: '김순남')
Professor.create(name: '김신식')
Professor.create(name: '김엘리')
Professor.create(name: '김영희')
Professor.create(name: '김용득')
Professor.create(name: '김용한')
Professor.create(name: '김용호')
Professor.create(name: '김은규')
Professor.create(name: '김정기')
Professor.create(name: '김종훈')
Professor.create(name: '김주연')
Professor.create(name: '김창남')
Professor.create(name: '김태우')
Professor.create(name: '김태욱')
Professor.create(name: '김학수')
Professor.create(name: '김한나')
Professor.create(name: '김혜인')
Professor.create(name: '김홍열')
Professor.create(name: '김활신')
Professor.create(name: '남일성')
Professor.create(name: '노은하')
Professor.create(name: '문성현')
Professor.create(name: '박경태')
Professor.create(name: '박경호')
Professor.create(name: '박미숙')
Professor.create(name: '박미정')
Professor.create(name: '박병상')
Professor.create(name: '박상선')
Professor.create(name: '박승호')
Professor.create(name: '박윤규')
Professor.create(name: '박은홍')
Professor.create(name: '박정식')
Professor.create(name: '박태식')
Professor.create(name: '박태영')
Professor.create(name: '박현수')
Professor.create(name: '백원담')
Professor.create(name: '사회교육원')
Professor.create(name: '사회진출실')
Professor.create(name: '상종열')
Professor.create(name: '서진환')
Professor.create(name: '손광식')
Professor.create(name: '신정완')
Professor.create(name: '신주백')
Professor.create(name: '신항우')
Professor.create(name: '안현배')
Professor.create(name: '안효상')
Professor.create(name: '양권석')
Professor.create(name: '엄순천')
Professor.create(name: '염찬희')
Professor.create(name: '오명숙')
Professor.create(name: '오세풍')
Professor.create(name: '원종우')
Professor.create(name: '원종호')
Professor.create(name: '유상신')
Professor.create(name: '유승호')
Professor.create(name: '유철규')
Professor.create(name: '이계우')
Professor.create(name: '이기형')
Professor.create(name: '이남주')
Professor.create(name: '이남호')
Professor.create(name: '이명춘')
Professor.create(name: '이미혜')
Professor.create(name: '이봉범')
Professor.create(name: '이상윤')
Professor.create(name: '이상훈')
Professor.create(name: '이숙진')
Professor.create(name: '이승이')
Professor.create(name: '이승진')
Professor.create(name: '이승희')
Professor.create(name: '이영환')
Professor.create(name: '이웅')
Professor.create(name: '이원석')
Professor.create(name: '이원정')
Professor.create(name: '이윤구')
Professor.create(name: '이종구')
Professor.create(name: '이주엽')
Professor.create(name: '이준희')
Professor.create(name: '이하규')
Professor.create(name: '이해신')
Professor.create(name: '임경순')
Professor.create(name: '임규찬')
Professor.create(name: '임성윤')
Professor.create(name: '임충규')
Professor.create(name: '임형')
Professor.create(name: '장수철')
Professor.create(name: '장승권')
Professor.create(name: '장영석')
Professor.create(name: '장화경')
Professor.create(name: '장희숙')
Professor.create(name: '전성원')
Professor.create(name: '정연식')
Professor.create(name: '정영희')
Professor.create(name: '정용권')
Professor.create(name: '정원오')
Professor.create(name: '정인철')
Professor.create(name: '정진철')
Professor.create(name: '정해구')
Professor.create(name: '정희경')
Professor.create(name: '조남경')
Professor.create(name: '조미혜')
Professor.create(name: '조병은')
Professor.create(name: '조옥희')
Professor.create(name: '조은기')
Professor.create(name: '조정위')
Professor.create(name: '조효제')
Professor.create(name: '주하영')
Professor.create(name: '지효선')
Professor.create(name: '진영종')
Professor.create(name: '진정석')
Professor.create(name: '채기화')
Professor.create(name: '채수진')
Professor.create(name: '최동호')
Professor.create(name: '최병구')
Professor.create(name: '최수일')
Professor.create(name: '최우석')
Professor.create(name: '최은주')
Professor.create(name: '최진봉')
Professor.create(name: '하남석')
Professor.create(name: '한긍수')
Professor.create(name: '한진일')
Professor.create(name: '한홍구')
Professor.create(name: '함병현')
Professor.create(name: '허성우')
Professor.create(name: '홍영경')
Professor.create(name: '홍은지')
Professor.create(name: '홍정수')
Professor.create(name: '홍준철')

